# Numpy Cheat Sheet

## Introduction

This notebook has various shortcuts, tips/tricks that I think might come in handy for various data science projects. 

### What Is Numpy?
NumPy is a powerful numerical computing library for Python. It provides support for arrays, matrices, and many mathematical functions to operate on these data structures.


### Installation

* To install NumPy, using `pip`:

```bash
pip install numpy
```

* To install NumPy, using `conda`:

```bash
conda install numpy
```

* To install NumPy using poetry:

```bash
poetry add numpy
```

### Importing NumPy

```python
import numpy as np
```

In [198]:
## import packages
import numpy as np

## Basics

* In NumPy, arrays can be used to represent both vectors and matrices. 
     * A vector is simply a one-dimensional array.
     * A matrix is a two-dimensional array.

### Creating Arrays

* The code below creates the following `Vector`

$$
\text{Vector} = \begin{bmatrix} 
1 & 2 & 3 & 4 & 5
\end{bmatrix}
$$

#### Creating Arrays from Python Lists

In [199]:
# From a list
array_from_list = np.array([1, 2, 3, 4, 5])
print("Array from list:", array_from_list)

Array from list: [1 2 3 4 5]


#### Creating Arrays from Tuples

In [200]:
# From a tuple
array_from_tuple = np.array((1, 2, 3, 4, 5))
print("Array from tuple:", array_from_tuple)

Array from tuple: [1 2 3 4 5]


* NumPy provides several functions to create arrays of different shapes and content.

#### Creating Arrays from a Range

In [201]:
# Using arange
array_arange = np.arange(0, 10, 2)
print("Array using arange:", array_arange)

Array using arange: [0 2 4 6 8]


In [202]:
## using arange and dtype
array_arange_float = np.arange(0, 10, 2, dtype=float)
print("Array using arange and dtype:", array_arange_float)

Array using arange and dtype: [0. 2. 4. 6. 8.]


In [203]:
# Using linspace
array_linspace = np.linspace(0, 1, 5)
print("Array using linspace:", array_linspace)

Array using linspace: [0.   0.25 0.5  0.75 1.  ]


In [204]:
## using linspace and dtype
array_linspace_int = np.linspace(0, 1, 5, dtype=int)
print("Array using linspace and dtype:", array_linspace_int)

Array using linspace and dtype: [0 0 0 0 1]


In [205]:
## using linspace and endpoint
array_linspace_endpoint = np.linspace(0, 1, 5, endpoint=False)
print("Array using linspace and endpoint:", array_linspace_endpoint)

Array using linspace and endpoint: [0.  0.2 0.4 0.6 0.8]


#### Creating array from a string

In [206]:
## creating array from string
array_from_string = np.fromstring('1 2 3 4 5', sep=' ')
print("Array from string:", array_from_string)

Array from string: [1. 2. 3. 4. 5.]


In [207]:
## array from non numeric string
char_arr = np.array(['Welcome to Math for ML!'])
print(char_arr)
print(char_arr.dtype)

['Welcome to Math for ML!']
<U23


In [208]:
## creating array from function
def my_func(i):
    return i % 4 + 1

array_from_func = np.fromfunction(my_func, (10,))
print("Array from function:", array_from_func)

Array from function: [1. 2. 3. 4. 1. 2. 3. 4. 1. 2.]


#### Creating default arrays

In [209]:
## using zeros
array_zeros = np.zeros((2, 3))
print("Array using zeros:", array_zeros)

Array using zeros: [[0. 0. 0.]
 [0. 0. 0.]]


In [210]:
## using ones
array_ones = np.ones((2, 3))
print("Array using ones:", array_ones)

Array using ones: [[1. 1. 1.]
 [1. 1. 1.]]


In [211]:
## using eye
array_eye = np.eye(3)
print("Array using eye:", array_eye)

Array using eye: [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [212]:
## using random
array_random = np.random.random((2, 3))
print("Array using random:", array_random)

Array using random: [[0.26768261 0.41601667 0.83514355]
 [0.08476781 0.17480053 0.7193971 ]]


In [213]:
## using random with dtype
array_random_int = np.random.randint(0, 100, (2, 3))
print("Array using random with dtype:", array_random_int)

Array using random with dtype: [[90 27 16]
 [10 70 18]]


In [214]:
## using empty
array_empty = np.empty((0, 3))
print("Array using empty:", array_empty)

Array using empty: []


### Multidimensional Arrays (Matrices)

#### Creating a 2D Matrix

* The code block below creates a matrix with 2 rows and 3 columns

$$
\text{Matrix} = \begin{bmatrix} 
1 & 2 & 3 \\ 
4 & 5 & 6 
\end{bmatrix}
$$

In [215]:
## from list of lists
matrix = np.array([[1, 2, 3], [4, 5, 6]])
print("Matrix:\n", matrix)

Matrix:
 [[1 2 3]
 [4 5 6]]


In [216]:
## printing dimensions
print("Dimensions of matrix:", matrix.ndim)

Dimensions of matrix: 2


$$
\text{Matrix} = \begin{bmatrix} 
1 & 2 & 3 \\ 
4 & 5 & 6 \\
7 & 8 & 9 
\end{bmatrix}
$$

In [217]:
# Creating a 3x3 matrix using a list of lists
matrix_3d = np.array([[1, 2, 3], [4, 5, 6],[7, 8, 9]])

print("3x3 matrix:\n", matrix_3d)
print("Shape of the 3D matrix:", matrix_3d.shape)

3x3 matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape of the 3D matrix: (3, 3)


### Array Attributes

NumPy arrays come with several useful attributes that can provide information about the array and its structure.

#### Array Shape

* The shape attribute returns a tuple representing the dimensions of the array.

In [218]:
## here we have 2 rows and 3 columns
array = np.array([[1, 2, 3], [4, 5, 6]])
print("Shape of the array:", array.shape)

Shape of the array: (2, 3)


#### Array dtype

The dtype attribute returns the data type of the elements in the array.

In [219]:
array = np.array([[1, 2, 3], [4, 5, 6]])
print("Data type of the array:", array.dtype)
# Output: Data type of the array: int64 (or int32 depending on the platform)

Data type of the array: int64


#### Array Size

* The `size` attribute returns the total number of elements in the array.

In [220]:
array = np.array([[1, 2, 3], [4, 5, 6]])
print("Total number of elements in the array:", array.size)

Total number of elements in the array: 6


#### Array Dimension

* The `ndim` attribute returns the number of dimensions (or axes) of the array.
* This is different from `dimension` in linear algebra.
     * A vector has 1 dimension.
     * A matrix has 2 dimensions.
     * A 3x3 matrix has 2 dimensions. 

In [221]:
array = np.array([1, 2, 3])
print("Number of dimensions of the array:", array.ndim)

Number of dimensions of the array: 1


In [222]:
array = np.array([[1, 2, 3], [4, 5, 6]])
print("Number of dimensions of the array:", array.ndim)

Number of dimensions of the array: 2


In [223]:
array = np.array([[[1, 2, 3], [4, 5, 6],[7, 8, 9]]])
print("Number of dimensions of the array:", array.ndim)

Number of dimensions of the array: 3


In [224]:
## 3D Matrix (tensor)
array = np.array([[[1, 2, 3], [4, 5, 6],[7, 8, 9]], [[10, 11, 12], [13, 14, 15],[16, 17, 18]]])
print("3D Matrix:\n", array)
print("Shape of the 3D matrix:", array.shape)
print("Number of dimensions of the 3D matrix:", array.ndim)

3D Matrix:
 [[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]
Shape of the 3D matrix: (2, 3, 3)
Number of dimensions of the 3D matrix: 3


#### Array Size in Bytes

* The `itemsize` attribute returns the size (in bytes) of each element in the array.

In [225]:
array = np.array([[1, 2, 3], [4, 5, 6]])
print("Size of each element in the array (in bytes):", array.itemsize)

Size of each element in the array (in bytes): 8


### Array Indexing & Slicing

* Indexing and slicing in NumPy allow you to access and modify elements within arrays. This is a fundamental aspect of working with NumPy arrays.
* Indices in NumPy arrays start at 0

#### Indexing

In [226]:
## indexing a 1D array
array = np.array([1, 2, 3, 4, 5])
print("Element at index 0:", array[0])
print("Element at index 1:", array[1])
print("Element at last index:", array[-1])
print("Element at second last index:", array[-2])

Element at index 0: 1
Element at index 1: 2
Element at last index: 5
Element at second last index: 4


In [227]:
## indexing a 2D array
array = np.array([[1, 2, 3], [4, 5, 6]])
print("Element at row 0 and column 0:", array[0, 0])
print("Element at row 0 and column 1:", array[0, 1])
print("Elements in last row:", array[-1])

Element at row 0 and column 0: 1
Element at row 0 and column 1: 2
Elements in last row: [4 5 6]


#### Slicing

* Slicing allows you to access a range of elements in an array. The syntax for slicing is `start:stop:step`.

In [228]:
## slicing a 1D array
array = np.array([1, 2, 3, 4, 5])
print("Elements from index 0 to 1:", array[0:2])
print("Elements from index 1:", array[1:])
print("Elements up to index 3:", array[:3])
print("Alternate elements starting from index 0:", array[0::2])

Elements from index 0 to 1: [1 2]
Elements from index 1: [2 3 4 5]
Elements up to index 3: [1 2 3]
Alternate elements starting from index 0: [1 3 5]


In [229]:
## slicing a 2D array
array = np.array([[1, 2, 3], [4, 5, 6]])
print("Elements from rows 0 to 1 and columns 0 to 1:\n", array[0:2, 0:2])
print("Elements from rows 0 to 1 and all columns:\n", array[0:2, :])
print("Elements from all rows and columns 1 to 2:\n", array[:, 1:])
print("Elements from all rows and first column:\n", array[:, 0])
print("Elements from rows 0 to 1 and alternate columns:\n", array[0:2, 0::2])
print("Elements from last row and all columns:\n", array[-1])
print("Element from last row and last column:\n", array[-1, -1])

Elements from rows 0 to 1 and columns 0 to 1:
 [[1 2]
 [4 5]]
Elements from rows 0 to 1 and all columns:
 [[1 2 3]
 [4 5 6]]
Elements from all rows and columns 1 to 2:
 [[2 3]
 [5 6]]
Elements from all rows and first column:
 [1 4]
Elements from rows 0 to 1 and alternate columns:
 [[1 3]
 [4 6]]
Elements from last row and all columns:
 [4 5 6]
Element from last row and last column:
 6


#### Fancy Indexing

* Fancy indexing allows you to access multiple elements at once using arrays of indices.

In [230]:
## fancy indexing a 1D array
array = np.array([1, 2, 3, 4, 5])
indices = [1, 3]
print("Elements at indices 1 and 3:", array[indices])

Elements at indices 1 and 3: [2 4]


In [231]:
## fancy indexing a 2D array
array = np.array([[1, 2, 3], [4, 5, 6]])
row_indices = [1]
column_indices = [0, 2]
print("Elements at row 1 and columns 0 and 2:\n", array[row_indices, column_indices])
print("All elements at columns 0 and 2:\n", array[:, column_indices])
print("All elements at row 1:\n", array[row_indices, :])

Elements at row 1 and columns 0 and 2:
 [4 6]
All elements at columns 0 and 2:
 [[1 3]
 [4 6]]
All elements at row 1:
 [[4 5 6]]


#### Boolean Indexing

* Boolean indexing allows you to select elements based on conditions.

In [232]:
## boolean indexing a 1D array
array = np.array([1, 2, 3, 4, 5])
mask = array > 2
print("Elements greater than 2:", array[mask])

Elements greater than 2: [3 4 5]


In [233]:
## boolean indexing a 2D array
array = np.array([[1, 2, 3], [4, 5, 6]])
mask = array > 2
print("Elements greater than 2:\n", array[mask])
print("Elements greater than 2 in first row:\n", array[0, mask[0]])

Elements greater than 2:
 [3 4 5 6]
Elements greater than 2 in first row:
 [3]


## Array Manipulation

### Reshaping Arrays

* You can change the shape of an array using the reshape method.

In [234]:
## reshaping a 1D array
array = np.array([1, 2, 3, 4, 5, 6])
reshaped_array = array.reshape(2, 3)
print("Original array:\n", array)
print("Reshaped array:\n", reshaped_array)
print("Shape of the original array:", array.shape)
print("Shape of the reshaped array:", reshaped_array.shape)

Original array:
 [1 2 3 4 5 6]
Reshaped array:
 [[1 2 3]
 [4 5 6]]
Shape of the original array: (6,)
Shape of the reshaped array: (2, 3)


In [235]:
## reshaping a 2D array
array = np.array([[1, 2, 3], [4, 5, 6]])
## we can only reshape to a size that has the same number of elements
reshaped_array = array.reshape(6)
print("Original array:\n", array)
print("Reshaped array:\n", reshaped_array)
print("Shape of the original array:", array.shape)
print("Shape of the reshaped array:", reshaped_array.shape)


Original array:
 [[1 2 3]
 [4 5 6]]
Reshaped array:
 [1 2 3 4 5 6]
Shape of the original array: (2, 3)
Shape of the reshaped array: (6,)


In [236]:
## reshaping 1d to 3d
array = np.array([1, 2, 3, 4, 5, 6])
reshaped_array = array.reshape(2, 1, 3)
print("Original array:\n", array)
print("Reshaped array:\n", reshaped_array)
print("Shape of the original array:", array.shape)
print("Shape of the reshaped array:", reshaped_array.shape)

Original array:
 [1 2 3 4 5 6]
Reshaped array:
 [[[1 2 3]]

 [[4 5 6]]]
Shape of the original array: (6,)
Shape of the reshaped array: (2, 1, 3)


### Transposing Arrays

* Transposing an array means to interchange the rows and columns of the array.
* Transpose changes the axes of an array. For 2D arrays, it switches rows and columns.

In [237]:
## transposing a 2D array
array = np.array([[1, 2, 3], [4, 5, 6]])
transposed_array = array.T
print("Original array:\n", array)
print("Transposed array:\n", transposed_array)
print("original array shape:", array.shape)
print("transposed array shape:", transposed_array.shape)


Original array:
 [[1 2 3]
 [4 5 6]]
Transposed array:
 [[1 4]
 [2 5]
 [3 6]]
original array shape: (2, 3)
transposed array shape: (3, 2)


### Array Concatenation & Stacking

* You can combine multiple arrays using concatenation and stacking.

In [238]:
## concatenating 1D arrays
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])
concatenated_array = np.concatenate([array1, array2])
print("Array 1:", array1)
print("Array 2:", array2)
print("Concatenated array:", concatenated_array)

Array 1: [1 2 3]
Array 2: [4 5 6]
Concatenated array: [1 2 3 4 5 6]


* 2D concatenation only works if the arrays have the same number of rows or columns.


In [239]:
## concatenating 2D arrays
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[7, 8, 9], [10, 11, 12]])
concatenated_array = np.concatenate([array1, array2])
print("Array 1:\n", array1)
print("Array 2:\n", array2)
print("Concatenated array:\n", concatenated_array)


Array 1:
 [[1 2 3]
 [4 5 6]]
Array 2:
 [[ 7  8  9]
 [10 11 12]]
Concatenated array:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [240]:
## concatenating 2D along columns using axis
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[7, 8, 9], [10, 11, 12]])
## default axis is 0 which concatenates along rows
concatenated_array = np.concatenate([array1, array2], axis=1)
print("Array 1:\n", array1)
print("Array 2:\n", array2)
print("Concatenated array:\n", concatenated_array)


Array 1:
 [[1 2 3]
 [4 5 6]]
Array 2:
 [[ 7  8  9]
 [10 11 12]]
Concatenated array:
 [[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


#### Vertical Stacking

In [241]:
## vertical stacking of 2D arrays sing vstack
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[7, 8, 9], [10, 11, 12]])
stacked_array = np.vstack([array1, array2])
print("Array 1:\n", array1)
print("Array 2:\n", array2)
print("Stacked array:\n", stacked_array)


Array 1:
 [[1 2 3]
 [4 5 6]]
Array 2:
 [[ 7  8  9]
 [10 11 12]]
Stacked array:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [242]:
## vertical stacking 1D arrays using vstack
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])
stacked_array = np.vstack([array1, array2])
print("Array 1:\n", array1)
print("Array 2:\n", array2)
print("Stacked array:\n", stacked_array)

Array 1:
 [1 2 3]
Array 2:
 [4 5 6]
Stacked array:
 [[1 2 3]
 [4 5 6]]


In [243]:
## vertical stacking 2D arrays using stack function and axis 1
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[7, 8, 9], [10, 11, 12]])
stacked_array = np.stack((array1, array2), axis=1)
print("Array 1:\n", array1)
print("Array 2:\n", array2)
print("Stacked array:\n", stacked_array)

Array 1:
 [[1 2 3]
 [4 5 6]]
Array 2:
 [[ 7  8  9]
 [10 11 12]]
Stacked array:
 [[[ 1  2  3]
  [ 7  8  9]]

 [[ 4  5  6]
  [10 11 12]]]


In [244]:
## vertical stacking 1D array using stack function and axis 1 
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])
stacked_array = np.stack((array1, array2), axis=1)
print("Array 1:", array1)
print("Array 2:", array2)
print("Stacked array:\n", stacked_array)

Array 1: [1 2 3]
Array 2: [4 5 6]
Stacked array:
 [[1 4]
 [2 5]
 [3 6]]


#### Horizontal Stacking

In [245]:
## horizontal stacking of 2D arrays using hstack
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])
stacked_array = np.hstack((array1, array2))
print("Array 1:\n", array1)
print("Array 2:\n", array2)
print("Stacked array:\n", stacked_array)

Array 1:
 [[1 2]
 [3 4]]
Array 2:
 [[5 6]
 [7 8]]
Stacked array:
 [[1 2 5 6]
 [3 4 7 8]]


In [246]:
## horizontal stacking of 1D arrays using hstack
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])
stacked_array = np.hstack((array1, array2))
print("Array 1:", array1)
print("Array 2:", array2)
print("Stacked array:", stacked_array)

Array 1: [1 2 3]
Array 2: [4 5 6]
Stacked array: [1 2 3 4 5 6]


In [247]:
## horizontal stacking 2D arrays using stack function and axis
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[7, 8, 9], [10, 11, 12]])
stacked_array = np.stack((array1, array2), axis=0)
print("Array 1:\n", array1)
print("Array 2:\n", array2)
print("Stacked array:\n", stacked_array)

Array 1:
 [[1 2 3]
 [4 5 6]]
Array 2:
 [[ 7  8  9]
 [10 11 12]]
Stacked array:
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [248]:
## horizontal stacking 1D using stack function and axis
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])
stacked_array = np.stack((array1, array2), axis=0)
print("Array 1:", array1)
print("Array 2:", array2)
print("Stacked array:\n", stacked_array)

Array 1: [1 2 3]
Array 2: [4 5 6]
Stacked array:
 [[1 2 3]
 [4 5 6]]


### Splitting Arrays

* You can split an array into multiple sub-arrays using split.

In [249]:
## splitting a 1D array
array = np.array([1, 2, 3, 4, 5, 6])
## split the array into 2 equal parts
split_arrays = np.split(array, 2)
print("Original array:", array)
print("Split arrays:", split_arrays)


Original array: [1 2 3 4 5 6]
Split arrays: [array([1, 2, 3]), array([4, 5, 6])]


In [250]:
## splitting a 2D array
array = np.array([[1, 2, 3], [4, 5, 6]])
## split the array into 2 equal parts along rows
split_arrays = np.split(array, 2)
print("Original array:\n", array)
print("Split arrays:", split_arrays)

Original array:
 [[1 2 3]
 [4 5 6]]
Split arrays: [array([[1, 2, 3]]), array([[4, 5, 6]])]


In [251]:
## splitting a 2D array along columns
array = np.array([[1, 2, 3], [4, 5, 6]])
## split the array into 3 equal parts along columns
split_arrays = np.split(array, 3, axis=1)
print("Original array:\n", array)
print("Split arrays:", split_arrays)
print("First split array:", split_arrays[0])

Original array:
 [[1 2 3]
 [4 5 6]]
Split arrays: [array([[1],
       [4]]), array([[2],
       [5]]), array([[3],
       [6]])]
First split array: [[1]
 [4]]


### Adding/Removing Elements

#### Appending Elements

In [252]:
## appending to a 1D array
array = np.array([1, 2, 3])
appended_array = np.append(array, [4, 5, 6])
print("Original array:", array)
print("Appended array:", appended_array)

Original array: [1 2 3]
Appended array: [1 2 3 4 5 6]


In [253]:
## appending to a 2D array
array = np.array([[1, 2, 3], [4, 5, 6]])
## append a row
appended_array = np.append(array, [[7, 8, 9]], axis=0)
print("Original array:\n", array)
print("Appended array:\n", appended_array)

## appending to a 2D array along columns
array = np.array([[1, 2, 3], [4, 5, 6]])
## append a column
appended_array = np.append(array, [[7], [8]], axis=1)
print("Original array:\n", array)
print("Appended array:\n", appended_array)


Original array:
 [[1 2 3]
 [4 5 6]]
Appended array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Original array:
 [[1 2 3]
 [4 5 6]]
Appended array:
 [[1 2 3 7]
 [4 5 6 8]]


#### Inserting Elements

In [254]:
## inserting into a 1D array
array = np.array([1, 2, 5, 6])
## insert 3 and 4 between 2 and 5
inserted_array = np.insert(array, 2, [3, 4])
print("Original array:", array)
print("Inserted array:", inserted_array)

Original array: [1 2 5 6]
Inserted array: [1 2 3 4 5 6]


In [255]:
## inserting into a 2D array
array = np.array([[1, 2, 3], [7, 8, 9]])
## insert a row between the 2 rows
inserted_array = np.insert(array, 1, [[4, 5, 6]], axis=0)
print("Original array:\n", array)
print("Inserted array:\n", inserted_array)

Original array:
 [[1 2 3]
 [7 8 9]]
Inserted array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [256]:
## inserting into a 2D array along columns
array = np.array([[1, 2, 3], [7, 8, 9]])
## insert a column between the 2 columns
inserted_array = np.insert(array, 1, [[4,5]], axis=1)
print("Original array:\n", array)
print("Inserved array:\n", inserted_array)

Original array:
 [[1 2 3]
 [7 8 9]]
Inserved array:
 [[1 4 2 3]
 [7 5 8 9]]


#### Deleting Elements

In [257]:
## deleting from a 1D array
array = np.array([1, 2, 3, 4, 5, 6])
## delete the element at index 2
deleted_array = np.delete(array, 2)
print("Original array:", array)
print("Deleted array:", deleted_array)


Original array: [1 2 3 4 5 6]
Deleted array: [1 2 4 5 6]


In [258]:
## deleting from a 2D array
array = np.array([[1, 2, 3], [4, 5, 6]])
## delete the row at index 1
deleted_array = np.delete(array, 1, axis=0)
print("Original array:\n", array)
print("Deleted array:\n", deleted_array)


Original array:
 [[1 2 3]
 [4 5 6]]
Deleted array:
 [[1 2 3]]


In [259]:
## deleting from a 2D array along columns
array = np.array([[1, 2, 3], [4, 5, 6]])
## delete the column at index 1
deleted_array = np.delete(array, 1, axis=1)
print("Original array:\n", array)
print("Deleted array:\n", deleted_array)


Original array:
 [[1 2 3]
 [4 5 6]]
Deleted array:
 [[1 3]
 [4 6]]


### Copying Arrays

* Copying arrays can be done with `copy` to create a deep copy, ensuring the original array is not modified.

In [260]:
## copying a 1D array
array = np.array([1, 2, 3])
copied_array = np.copy(array)

## adding an element to the copied array will not affect the original array
copied_array[0] = 0

print("Original array:", array)
print("Copied array:", copied_array)


Original array: [1 2 3]
Copied array: [0 2 3]


## Array Operations

### Basic Operations

* NumPy supports element-wise arithmetic operations.

In [261]:
## create 2 arrays for arithmetic operations
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

#### Addition

In [262]:
## element-wise addition
addition = array1 + array2
print("Element-wise addition:", addition)

Element-wise addition: [5 7 9]


#### Substraction

In [263]:
## element-wise subtraction
subtraction = array1 - array2
print("Element-wise subtraction:", subtraction)

Element-wise subtraction: [-3 -3 -3]


#### Multiplication

In [264]:
## element-wise multiplication
multiplication = array1 * array2
print("Element-wise multiplication:", multiplication)

Element-wise multiplication: [ 4 10 18]


#### Division

In [265]:
## element-wise division
division = array1 / array2
print("Element-wise division:", division)

Element-wise division: [0.25 0.4  0.5 ]


#### Square Root

In [266]:
## element-wise square root
square_root = np.sqrt(array1)
print("Element-wise square root:", square_root)

Element-wise square root: [1.         1.41421356 1.73205081]


#### Exponential

In [267]:
## element-wise exponentiation
exponentiation = np.exp(array1)
print("Element-wise exponentiation:", exponentiation)

Element-wise exponentiation: [ 2.71828183  7.3890561  20.08553692]


#### Sine

In [268]:
## element-wise sine
sine = np.sin(array1)
print("Element-wise sine:", sine)

Element-wise sine: [0.84147098 0.90929743 0.14112001]


### Statistical Operations

* Important to note here, `axis` works slightly different than our earlier interpretation of rows and columns.
* For following functions `axis` decided which axis to perform the operation on. So if `axis=0`, the operation will be performed on the rows and output will be same number of columns. If `axis=1`, the operation will be performed on the columns and output will be same number of rows.

In [269]:
## sample 1D array for statistical operations
array_1d = np.array([1, 2, 3, 4, 5])

## sample 2D array for statistical operations
array_2d = np.array([[-1, 2, 3], [4, 5, 6]])

#### Mininum

In [270]:
## minimum of a 1D array
minimum = np.min(array_1d)
print("Minimum of 1D array:", minimum)

## minimum of a 2D array
minimum = np.min(array_2d)
print("Minimum of 2D array:", minimum)

Minimum of 1D array: 1
Minimum of 2D array: -1


In [271]:
## minimum of a 2D array along columns
minimum = np.min(array_2d, axis=1)
print("minimum of 2D array along columns:", minimum)

minimum of 2D array along columns: [-1  4]


In [272]:
## minimum of a 2D array along rows
minimum = np.min(array_2d, axis=0)
print("minimum of 2D array along rows:", minimum)

minimum of 2D array along rows: [-1  2  3]


#### Maximum

In [273]:
## maximum of a 1D array
maximum = np.max(array_1d)
print("Maximum of 1D array:", maximum)

## maximum of a 2D array
maximum = np.max(array_2d)
print("Maximum of 2D array:", maximum)

Maximum of 1D array: 5
Maximum of 2D array: 6


In [274]:
## maximum of a 2D array along columns
maximum = np.max(array_2d, axis=1)
print("Maximum of 2D array along columns:", maximum)

Maximum of 2D array along columns: [3 6]


In [275]:
## maximum of a 2D array along rows
maximum = np.max(array_2d, axis=0)
print("Maximum of 2D array along rows:", maximum)

Maximum of 2D array along rows: [4 5 6]


#### Mean

In [276]:
## mean of a 1D array
mean = np.mean(array_1d)
print("Mean of 1D array:", mean)

## mean of a 2D array
mean = np.mean(array_2d)
print("Mean of 2D array:", mean)

Mean of 1D array: 3.0
Mean of 2D array: 3.1666666666666665


In [277]:
## mean of a 2D array along columns
mean = np.mean(array_2d, axis=1)
print("Mean of 2D array along columns:", mean)

Mean of 2D array along columns: [1.33333333 5.        ]


In [278]:
## mean of a 2D array along rows
mean = np.mean(array_2d, axis=0)
print("Mean of 2D array along rows:", mean)


Mean of 2D array along rows: [1.5 3.5 4.5]


#### Median

In [279]:
## median of a 1D array
median = np.median(array_1d)
print("Median of 1D array:", median)

Median of 1D array: 3.0


In [280]:
## median of a 2D array
median = np.median(array_2d)
print("Median of 2D array:", median)

Median of 2D array: 3.5


In [281]:
## median of a 2D array along columns 
median = np.median(array_2d, axis=1)
print("Median of 2D array along columns:", median)

Median of 2D array along columns: [2. 5.]


In [282]:
## median of a 2D array along rows
median = np.median(array_2d, axis=0)
print("Median of 2D array along rows:", median)

Median of 2D array along rows: [1.5 3.5 4.5]


#### Standard Deviation

In [283]:
## standard deviation of a 1D array
std_dev = np.std(array_1d)
print("Standard deviation of 1D array:", std_dev)

Standard deviation of 1D array: 1.4142135623730951


In [284]:
## standard deviation of a 2D array
std_dev = np.std(array_2d)
print("Standard deviation of 2D array:", std_dev)

Standard deviation of 2D array: 2.266911751455907


In [285]:
## standard deviation of a 2D array along columns
std_dev = np.std(array_2d, axis=1)
print("Standard deviation of 2D array along columns:", std_dev)

Standard deviation of 2D array along columns: [1.69967317 0.81649658]


In [286]:
## standard deviation of a 2D array along rows
std_dev = np.std(array_2d, axis=0)
print("Standard deviation of 2D array along rows:", std_dev)

Standard deviation of 2D array along rows: [2.5 1.5 1.5]


#### Sum

In [287]:
## sum of a 1D array
sum = np.sum(array_1d)
print("Sum of 1D array:", sum)

Sum of 1D array: 15


In [288]:
## sum of a 2D array
sum = np.sum(array_2d)
print("Sum of 2D array:", sum)

Sum of 2D array: 19


In [289]:
## sum of a 2D array along columns
sum = np.sum(array_2d, axis=1)
print("Sum of 2D array along columns:", sum)

Sum of 2D array along columns: [ 4 15]


In [290]:
## sum of a 2D array along rows
sum = np.sum(array_2d, axis=0)
print("Sum of 2D array along rows:", sum)

Sum of 2D array along rows: [3 7 9]


#### Cumulative Sum

In [291]:
## cummulative sum of a 1D array
cum_sum = np.cumsum(array_1d)
print("Cummulative sum of 1D array:", cum_sum)

Cummulative sum of 1D array: [ 1  3  6 10 15]


In [292]:
## cummulative sum of a 2D array
cum_sum = np.cumsum(array_2d)
print("Cummulative sum of 2D array:", cum_sum)

Cummulative sum of 2D array: [-1  1  4  8 13 19]


In [293]:
## cummulative sum of a 2D array along columns
cum_sum = np.cumsum(array_2d, axis=1)
print("Cummulative sum of 2D array along columns:", cum_sum)

Cummulative sum of 2D array along columns: [[-1  1  4]
 [ 4  9 15]]


In [294]:
## cummulative sum of a 2D array along rows
cum_sum = np.cumsum(array_2d, axis=0)
print("Cummulative sum of 2D array along rows:", cum_sum)

Cummulative sum of 2D array along rows: [[-1  2  3]
 [ 3  7  9]]


### Sorting & Searching

#### Sorting

In [295]:
## sorting 1D array
array = np.array([3, 2, 1, 4, 5])
sorted_array = np.sort(array)
print("Original array:", array)
print("Sorted array:", sorted_array)

Original array: [3 2 1 4 5]
Sorted array: [1 2 3 4 5]


In [296]:
## sorting 2D array
array = np.array([[3, 2, 1], [4, 5, 6]])
sorted_array = np.sort(array)
print("Original array:\n", array)
print("Sorted array:\n", sorted_array)

Original array:
 [[3 2 1]
 [4 5 6]]
Sorted array:
 [[1 2 3]
 [4 5 6]]


In [297]:
## sorting 2D array along columns
array = np.array([[3, 2, 1], [4, 5, 6]])
sorted_array = np.sort(array, axis=1)
print("Original array:\n", array)
print("Sorted array along columns:\n", sorted_array)


Original array:
 [[3 2 1]
 [4 5 6]]
Sorted array along columns:
 [[1 2 3]
 [4 5 6]]


In [298]:
## sorting 2D array along rows
array = np.array([[3, 2, 1], [4, 5, 6]])
sorted_array = np.sort(array, axis=0)
print("Original array:\n", array)
print("Sorted array along rows:\n", sorted_array)

Original array:
 [[3 2 1]
 [4 5 6]]
Sorted array along rows:
 [[3 2 1]
 [4 5 6]]


#### Searching

In [299]:
## Searching for an element in a 1D array
array = np.array([1, 2, 3, 4, 5])
## search for 3 in the array
index = np.where(array == 3)
print("Original array:", array)
print("Index of 3:", index)

Original array: [1 2 3 4 5]
Index of 3: (array([2]),)


In [300]:
## Searching for an element in a 2D array
array = np.array([[1, 2, 3], [4, 5, 6]])
## search for 3 in the array
index = np.where(array == 3)
print("Original array:\n", array)
print("Index of 3:", index)

Original array:
 [[1 2 3]
 [4 5 6]]
Index of 3: (array([0]), array([2]))


In [301]:
## search with duplicates
array = np.array([1, 2, 3, 4, 5, 3])
## search for 3 in the array
index = np.where(array == 3)
print("Original array:", array)
print("Index of 3:", index)

Original array: [1 2 3 4 5 3]
Index of 3: (array([2, 5]),)


#### Find min/max index

In [302]:
## search for min/max value index in a 1D array
array = np.array([1, 2, 3, 4, 5])
## index of minimum value
min_index = np.argmin(array)
## index of maximum value
max_index = np.argmax(array)
print("Original array:", array)
print("Index of minimum value:", min_index)
print("Index of maximum value:", max_index)

Original array: [1 2 3 4 5]
Index of minimum value: 0
Index of maximum value: 4


In [303]:
## search for min/max value index in a 2D array
array = np.array([[1, 2, 3], [4, 5, 6]])
## index of minimum value
min_index = np.argmin(array)
## index of maximum value
max_index = np.argmax(array)
print("Original array:\n", array)
print("Index of minimum value:", min_index)
print("Index of maximum value:", max_index)


Original array:
 [[1 2 3]
 [4 5 6]]
Index of minimum value: 0
Index of maximum value: 5


In [304]:
## search for min/max value index in a 2D array along columns
array = np.array([[1, 2, 3], [4, 5, 6]])
## index of minimum value along columns
min_index = np.argmin(array, axis=1)
## index of maximum value along columns
max_index = np.argmax(array, axis=1)
print("Original array:\n", array)
print("Index of minimum value along columns:", min_index)
print("Index of maximum value along columns:", max_index)


Original array:
 [[1 2 3]
 [4 5 6]]
Index of minimum value along columns: [0 0]
Index of maximum value along columns: [2 2]


In [305]:
## search for min/max value index in a 2D array along rows
array = np.array([[1, 2, 3], [4, 5, 6]])
## index of minimum value along rows
min_index = np.argmin(array, axis=0)
## index of maximum value along rows
max_index = np.argmax(array, axis=0)
print("Original array:\n", array)
print("Index of minimum value along rows:", min_index)
print("Index of maximum value along rows:", max_index)


Original array:
 [[1 2 3]
 [4 5 6]]
Index of minimum value along rows: [0 0 0]
Index of maximum value along rows: [1 1 1]


## Linear Algebra

### Vectors & Matrices

$$
\overrightarrow{v} = \begin{bmatrix}
1 && 2 && 3
\end{bmatrix}
$$

In [306]:
## vector v can be represented as 1D array
v = np.array([1, 2, 3])
print("Vector v:", v)

Vector v: [1 2 3]


3x3 Matrix

$$
\text{Matrix} = \begin{bmatrix}
1 && 2 && 3 \\
4 && 5 && 6 \\
7 && 8 && 9
\end{bmatrix}
$$

In [307]:
## 3x3 matrix A can be represented as 2D array
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Matrix A:\n", A)

Matrix A:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


### Matrix Operations

#### Matrix Multiplication

In [308]:
## create two matrices
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

## matrix multiplication
C = np.matmul(A, B)
print("Matrix A:\n", A)
print("Matrix B:\n", B)
print("Matrix C (A*B):\n", C)

Matrix A:
 [[1 2]
 [3 4]]
Matrix B:
 [[5 6]
 [7 8]]
Matrix C (A*B):
 [[19 22]
 [43 50]]


#### Dot Product

In [309]:
## dot product of matrices
C = np.dot(A, B)
print("Matrix C (A.B):\n", C)

Matrix C (A.B):
 [[19 22]
 [43 50]]


In [310]:
## vector matrix dot product
v = np.array([1, 2])
A = np.array([[1, 2], [3, 4]])

## dot product of vector and matrix
u = np.dot(v, A)
print("Vector v:", v)
print("Matrix A:\n", A)
print("Vector-matrix dot product:", u)

Vector v: [1 2]
Matrix A:
 [[1 2]
 [3 4]]
Vector-matrix dot product: [ 7 10]


#### Cross Product

In [311]:
## matrix cross product
A = np.array([1, 2, 3])
B = np.array([4, 5, 6])

## cross product of matrices
C = np.cross(A, B)
print("Matrix A:", A)
print("Matrix B:", B)
print("Matrix C (AxB):", C)

Matrix A: [1 2 3]
Matrix B: [4 5 6]
Matrix C (AxB): [-3  6 -3]


#### Solving Linear Equations

In [312]:
## cooefficient matrix
A = np.array([[3, 1], [1, 2]])

## RHS vector
b = np.array([9, 8])

## solving the system of linear equations Ax = b
x = np.linalg.solve(A, b)
print("Matrix A:\n", A)
print("RHS vector b:", b)
print("Solution x:", x)

Matrix A:
 [[3 1]
 [1 2]]
RHS vector b: [9 8]
Solution x: [2. 3.]


#### Matrix Inversion

In [313]:
## create a matrix for matrix inversion
A = np.array([[1, 2], [3, 4]])

## inverse of the matrix
A_inv = np.linalg.inv(A)
print("Matrix A:\n", A)
print("Inverse of matrix A:\n", A_inv)

Matrix A:
 [[1 2]
 [3 4]]
Inverse of matrix A:
 [[-2.   1. ]
 [ 1.5 -0.5]]


#### Determinant Calculation

In [315]:
## create a matrix for determinant calculation
A = np.array([[1, 2], [3, 4]])

## determinant of the matrix
det_A = np.linalg.det(A)
print("Matrix A:\n", A)
print("Determinant of matrix A:", det_A)

Matrix A:
 [[1 2]
 [3 4]]
Determinant of matrix A: -2.0000000000000004


#### Eigenvalues & Eigenvectors

In [316]:
## create a matrix for eigenvalues and eigenvectors calculation
A = np.array([[1, 2], [3, 4]])

## eigenvalues and eigenvectors of the matrix
eigenvalues, eigenvectors = np.linalg.eig(A)
print("Matrix A:\n", A)
print("Eigenvalues of matrix A:", eigenvalues)
print("Eigenvectors of matrix A:\n", eigenvectors)

Matrix A:
 [[1 2]
 [3 4]]
Eigenvalues of matrix A: [-0.37228132  5.37228132]
Eigenvectors of matrix A:
 [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


#### Creating Identity Matrix

In [317]:
## createing identity matrix
I = np.eye(3)
print("Identity matrix I:\n", I)

Identity matrix I:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### Creating Covariance Matrix

In [321]:
## sample matrix to create covariance matrix
X = np.array([[1, 2], [3, 4], [5, 6]])

## covariance matrix
cov_X = np.cov(X.T, bias=True)

print("Matrix X:\n", X)
print("Covariance matrix of X:\n", cov_X)

Matrix X:
 [[1 2]
 [3 4]
 [5 6]]
Covariance matrix of X:
 [[2.66666667 2.66666667]
 [2.66666667 2.66666667]]


## Helpful Functions

### Random Numbers

In [322]:
## generatate single random number between 0 and 1
random_number = np.random.rand()
print("Random number between 0 and 1:", random_number)

Random number between 0 and 1: 0.9153544971751577


In [323]:
## generate array of random numbers
random_array = np.random.rand(3)
print("Array of random numbers:", random_array)

Array of random numbers: [0.57415201 0.24696697 0.72816017]


In [324]:
## generate 2D array of random numbers
random_array = np.random.rand(2, 3)
print("2D array of random numbers:\n", random_array)

2D array of random numbers:
 [[0.10018828 0.70428584 0.72369213]
 [0.62724012 0.88293572 0.6177458 ]]


### Random Sampling

In [326]:
## generate random integers between 0 and 10
random_int = np.random.randint(0, 10, size=5)
print("Random integers between 0 and 10:", random_int)

## generate 2D array of random integers between 0 and 10
random_int = np.random.randint(0, 10, size=(3, 3))
print("2D array of random integers between 0 and 10:\n", random_int)

Random integers between 0 and 10: [1 3 6 5 0]
2D array of random integers between 0 and 10:
 [[9 7 5]
 [7 7 3]
 [4 0 5]]


### Random Distributions

In [328]:
## generate random numbers from a normal distribution
random_numbers = np.random.randn(5)
print("Random numbers from a normal distribution:", random_numbers)

## generate 2D array of random numbers from a normal distribution
random_numbers = np.random.uniform(0,10,size=5)
print("2D array of random numbers from a normal distribution:\n", random_numbers)

# Generate random numbers from a Poisson distribution
poisson_dist = np.random.poisson(5, size=5)
print("Random numbers from a Poisson distribution:", poisson_dist)

Random numbers from a normal distribution: [-1.00203599 -0.05004371 -1.26083386 -0.53836791 -1.57009665]
2D array of random numbers from a normal distribution:
 [7.85363376 7.17850328 8.77724785 9.89032042 2.82241408]
Random numbers from a Poisson distribution: [4 3 5 7 0]


### Setting Seed for Reproducibility

In [329]:
# Set the seed
np.random.seed(42)

# Generate random numbers
random_array_1 = np.random.rand(5)
print("Random array with seed 42:", random_array_1)

# Reset the seed and generate again
np.random.seed(42)
random_array_2 = np.random.rand(5)
print("Random array with seed 42 (again):", random_array_2)

Random array with seed 42: [0.37454012 0.95071431 0.73199394 0.59865848 0.15601864]
Random array with seed 42 (again): [0.37454012 0.95071431 0.73199394 0.59865848 0.15601864]


## Advanced Topics

### Broadcasting

* Broadcasting is a powerful feature in NumPy that allows you to perform arithmetic operations on arrays of different shapes. 
* It automatically expands the smaller array to match the shape of the larger array.

In [344]:
# Create two arrays of different shapes
array1 = np.array([1, 2, 3])
array2 = np.array([[1], 
                   [2], 
                   [3]])

# Broadcasting addition
result = array1 + array2
print("Broadcasted addition:\n", result)

Broadcasted addition:
 [[2 3 4]
 [3 4 5]
 [4 5 6]]


### Vectorization

* Vectorization refers to the process of converting iterative operations into vector operations, which are executed more efficiently by NumPy.

In [345]:
# Iterative operation (slow)
array = np.arange(1000000)
squared_iter = [x**2 for x in array]

# Vectorized operation (fast)
squared_vectorized = np.square(array)

### Memory Layout

* Understanding memory layout can help optimize performance. 
* NumPy arrays can be stored in either C-contiguous (row-major) or F-contiguous (column-major) order.

In [346]:
# Create arrays with different memory layouts
array_c = np.array([[1, 2, 3], [4, 5, 6]], order='C')
array_f = np.array([[1, 2, 3], [4, 5, 6]], order='F')

print("C-contiguous array:\n", array_c)
print("F-contiguous array:\n", array_f)

C-contiguous array:
 [[1 2 3]
 [4 5 6]]
F-contiguous array:
 [[1 2 3]
 [4 5 6]]


### Structured Arrays

* Structured arrays allow you to define arrays with different data types for each element.

In [347]:
# Define a structured array with different data types
data = np.array([(1, 'Alice', 3.5), (2, 'Bob', 2.7)], 
                dtype=[('id', 'i4'), ('name', 'U10'), ('score', 'f4')])

print("Structured array:\n", data)
print("Names:", data['name'])


Structured array:
 [(1, 'Alice', 3.5) (2, 'Bob', 2.7)]
Names: ['Alice' 'Bob']


### Fancy Indexing

* Fancy indexing allows you to access and modify arrays using arrays of indices.

In [348]:
# Create an array
array = np.array([10, 20, 30, 40, 50])

# Fancy indexing with a list of indices
indices = [0, 2, 4]
print("Elements at indices 0, 2, and 4:", array[indices])

# Modify elements at specific indices
array[indices] = -1
print("Array after modification:", array)

Elements at indices 0, 2, and 4: [10 30 50]
Array after modification: [-1 20 -1 40 -1]


### Comparing Array Elements using isclose()

### Converting Array Elment Types

## Tips & Tricks

### Avoid Loops

* Use NumPy's vectorized operations instead of Python loops. Vectorized operations are much faster because they are implemented in C and avoid the overhead of Python loops.

In [333]:
array = np.arange(1000000)
total = 0

In [334]:
## avoid using a loop (slow)
for i in array:
    total += i

In [335]:
# Using vectorized operation (fast)
total = np.sum(array)

### Use Built-in Functions

* NumPy's built-in functions are optimized for performance. Whenever possible, use them instead of writing custom code.

In [336]:
# Custom code (slow)
array = np.arange(1000000)
squared = np.array([i**2 for i in array])

In [337]:
# Built-in function (fast)
squared = np.square(array)

### Memory Layout

* Be aware of the memory layout of arrays. Contiguous memory access (C-order or F-order) is faster than non-contiguous access.

In [338]:
# C-order (row-major)
array_c = np.array([[1, 2, 3], [4, 5, 6]], order='C')

# F-order (column-major)
array_f = np.array([[1, 2, 3], [4, 5, 6]], order='F')

### Copy vs. View

Understand the difference between copying an array and creating a view. Modifying a view will affect the original array, whereas copying will not.

In [340]:
array = np.array([1, 2, 3])
print("Original array:", array)
# Creating a view
view = array[:]
view[0] = 99
print("Original array (view modified):", array)

# Creating a copy
copy = array.copy()
copy[0] = 100
print("Original array (copy modified):", array)
print("Copy of the array:", copy)

Original array: [1 2 3]
Original array (view modified): [99  2  3]
Original array (copy modified): [99  2  3]
Copy of the array: [100   2   3]


### Avoid Modifying Arrays in Place

* Modifying arrays in place can lead to unexpected results, especially when broadcasting is involved. Always consider creating new arrays for complex operations.

In [341]:
array = np.array([1, 2, 3])

# Modifying in place (can be risky)
array += 1

# Creating a new array (safer)
new_array = array + 1

### Handling NaNs

* NumPy provides functions to handle NaNs (Not a Number). 
* Use `np.isnan`, `np.nan_to_num`, and other related functions to manage NaNs in your data.

In [342]:
array = np.array([1, 2, np.nan, 4])

# Check for NaNs
isnan = np.isnan(array)
print("NaNs in array:", isnan)

# Replace NaNs with 0
array_no_nan = np.nan_to_num(array)
print("Array with NaNs replaced:", array_no_nan)

NaNs in array: [False False  True False]
Array with NaNs replaced: [1. 2. 0. 4.]


### Use Assestions for debugging

* Use assertions to check that arrays meet certain conditions, such as shape, type, and value ranges.

In [343]:
array = np.array([1, 2, 3])
assert array.shape == (3,)
assert array.dtype == np.int64

## Visualization

## Applications in Linear Algebra

### Examples of Solving System of Linear Equations

### Examples of Matrix Decompositions

### Real World Applications

#### Data Transformation

#### Dimensionality Reduction

## Image Handling