# Numpy Cheat Sheet

## Introduction

This notebook has various shortcuts, tips/tricks that I think might come in handy for various data science projects. 

### What Is Numpy?
NumPy is a powerful numerical computing library for Python. It provides support for arrays, matrices, and many mathematical functions to operate on these data structures.


### Installation

* To install NumPy, using `pip`:

```bash
pip install numpy
```

* To install NumPy, using `conda`:

```bash
conda install numpy
```

* To install NumPy using poetry:

```bash
poetry add numpy
```

### Importing NumPy

```python
import numpy as np
```

In [1]:
## import packages
import numpy as np

## Basics

* In NumPy, arrays can be used to represent both vectors and matrices. 
     * A vector is simply a one-dimensional array.
     * A matrix is a two-dimensional array.

### Creating Arrays

* The code below creates the following `Vector`

$$
\text{Vector} = \begin{bmatrix} 
1 & 2 & 3 & 4 & 5
\end{bmatrix}
$$

#### Creating Arrays from Python Lists

In [2]:
# From a list
array_from_list = np.array([1, 2, 3, 4, 5])
print("Array from list:", array_from_list)

Array from list: [1 2 3 4 5]


#### Creating Arrays from Tuples

In [3]:
# From a tuple
array_from_tuple = np.array((1, 2, 3, 4, 5))
print("Array from tuple:", array_from_tuple)

Array from tuple: [1 2 3 4 5]


* NumPy provides several functions to create arrays of different shapes and content.

#### Creating Arrays from a Range

In [4]:
# Using arange
array_arange = np.arange(0, 10, 2)
print("Array using arange:", array_arange)

Array using arange: [0 2 4 6 8]


In [5]:
## using arange and dtype
array_arange_float = np.arange(0, 10, 2, dtype=float)
print("Array using arange and dtype:", array_arange_float)

Array using arange and dtype: [0. 2. 4. 6. 8.]


In [6]:
# Using linspace
array_linspace = np.linspace(0, 1, 5)
print("Array using linspace:", array_linspace)

Array using linspace: [0.   0.25 0.5  0.75 1.  ]


In [7]:
## using linspace and dtype
array_linspace_int = np.linspace(0, 1, 5, dtype=int)
print("Array using linspace and dtype:", array_linspace_int)

Array using linspace and dtype: [0 0 0 0 1]


In [8]:
## using linspace and endpoint
array_linspace_endpoint = np.linspace(0, 1, 5, endpoint=False)
print("Array using linspace and endpoint:", array_linspace_endpoint)

Array using linspace and endpoint: [0.  0.2 0.4 0.6 0.8]


#### Creating array from a string

In [9]:
## creating array from string
array_from_string = np.fromstring('1 2 3 4 5', sep=' ')
print("Array from string:", array_from_string)

Array from string: [1. 2. 3. 4. 5.]


In [10]:
## array from non numeric string
char_arr = np.array(['Welcome to Math for ML!'])
print(char_arr)
print(char_arr.dtype)

['Welcome to Math for ML!']
<U23


In [11]:
## creating array from function
def my_func(i):
    return i % 4 + 1

array_from_func = np.fromfunction(my_func, (10,))
print("Array from function:", array_from_func)

Array from function: [1. 2. 3. 4. 1. 2. 3. 4. 1. 2.]


#### Creating default arrays

In [12]:
## using zeros
array_zeros = np.zeros((2, 3))
print("Array using zeros:", array_zeros)

Array using zeros: [[0. 0. 0.]
 [0. 0. 0.]]


In [13]:
## using ones
array_ones = np.ones((2, 3))
print("Array using ones:", array_ones)

Array using ones: [[1. 1. 1.]
 [1. 1. 1.]]


In [14]:
## using eye
array_eye = np.eye(3)
print("Array using eye:", array_eye)

Array using eye: [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [15]:
## using random
array_random = np.random.random((2, 3))
print("Array using random:", array_random)

Array using random: [[0.88932063 0.99165036 0.39156314]
 [0.29602009 0.33851889 0.8366207 ]]


In [16]:
## using random with dtype
array_random_int = np.random.randint(0, 100, (2, 3))
print("Array using random with dtype:", array_random_int)

Array using random with dtype: [[95 98 38]
 [72 14  3]]


In [17]:
## using empty
array_empty = np.empty((0, 3))
print("Array using empty:", array_empty)

Array using empty: []


### Multidimensional Arrays (Matrices)

#### Creating a 2D Matrix

* The code block below creates a matrix with 2 rows and 3 columns

$$
\text{Matrix} = \begin{bmatrix} 
1 & 2 & 3 \\ 
4 & 5 & 6 
\end{bmatrix}
$$

In [18]:
## from list of lists
matrix = np.array([[1, 2, 3], [4, 5, 6]])
print("Matrix:\n", matrix)

Matrix:
 [[1 2 3]
 [4 5 6]]


In [27]:
## printing dimensions
print("Dimensions of matrix:", matrix.ndim)

Dimensions of matrix: 2


$$
\text{Matrix} = \begin{bmatrix} 
1 & 2 & 3 \\ 
4 & 5 & 6 \\
7 & 8 & 9 
\end{bmatrix}
$$

In [36]:
# Creating a 3x3 matrix using a list of lists
matrix_3d = np.array([[1, 2, 3], [4, 5, 6],[7, 8, 9]])

print("3x3 matrix:\n", matrix_3d)
print("Shape of the 3D matrix:", matrix_3d.shape)

3x3 matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape of the 3D matrix: (3, 3)


### Array Attributes

NumPy arrays come with several useful attributes that can provide information about the array and its structure.

#### Array Shape

* The shape attribute returns a tuple representing the dimensions of the array.

In [20]:
## here we have 2 rows and 3 columns
array = np.array([[1, 2, 3], [4, 5, 6]])
print("Shape of the array:", array.shape)

Shape of the array: (2, 3)


#### Array dtype

The dtype attribute returns the data type of the elements in the array.

In [21]:
array = np.array([[1, 2, 3], [4, 5, 6]])
print("Data type of the array:", array.dtype)
# Output: Data type of the array: int64 (or int32 depending on the platform)

Data type of the array: int64


#### Array Size

* The `size` attribute returns the total number of elements in the array.

In [22]:
array = np.array([[1, 2, 3], [4, 5, 6]])
print("Total number of elements in the array:", array.size)

Total number of elements in the array: 6


#### Array Dimension

* The `ndim` attribute returns the number of dimensions (or axes) of the array.
* This is different from `dimension` in linear algebra.
     * A vector has 1 dimension.
     * A matrix has 2 dimensions.
     * A 3x3 matrix has 2 dimensions. 

In [23]:
array = np.array([1, 2, 3])
print("Number of dimensions of the array:", array.ndim)

Number of dimensions of the array: 1


In [24]:
array = np.array([[1, 2, 3], [4, 5, 6]])
print("Number of dimensions of the array:", array.ndim)

Number of dimensions of the array: 2


In [25]:
array = np.array([[[1, 2, 3], [4, 5, 6],[7, 8, 9]]])
print("Number of dimensions of the array:", array.ndim)

Number of dimensions of the array: 3


In [37]:
## 3D Matrix (tensor)
array = np.array([[[1, 2, 3], [4, 5, 6],[7, 8, 9]], [[10, 11, 12], [13, 14, 15],[16, 17, 18]]])
print("3D Matrix:\n", array)
print("Shape of the 3D matrix:", array.shape)
print("Number of dimensions of the 3D matrix:", array.ndim)

3D Matrix:
 [[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]
Shape of the 3D matrix: (2, 3, 3)
Number of dimensions of the 3D matrix: 3


#### Array Size in Bytes

* The `itemsize` attribute returns the size (in bytes) of each element in the array.

In [38]:
array = np.array([[1, 2, 3], [4, 5, 6]])
print("Size of each element in the array (in bytes):", array.itemsize)

Size of each element in the array (in bytes): 8


### Array Indexing & Slicing

* Indexing and slicing in NumPy allow you to access and modify elements within arrays. This is a fundamental aspect of working with NumPy arrays.
* Indices in NumPy arrays start at 0

#### Indexing

In [50]:
## indexing a 1D array
array = np.array([1, 2, 3, 4, 5])
print("Element at index 0:", array[0])
print("Element at index 1:", array[1])
print("Element at last index:", array[-1])
print("Element at second last index:", array[-2])

Element at index 0: 1
Element at index 1: 2
Element at last index: 5
Element at second last index: 4


In [52]:
## indexing a 2D array
array = np.array([[1, 2, 3], [4, 5, 6]])
print("Element at row 0 and column 0:", array[0, 0])
print("Element at row 0 and column 1:", array[0, 1])
print("Elements in last row:", array[-1])

Element at row 0 and column 0: 1
Element at row 0 and column 1: 2
Elements in last row: [4 5 6]


#### Slicing

* Slicing allows you to access a range of elements in an array. The syntax for slicing is `start:stop:step`.

In [42]:
## slicing a 1D array
array = np.array([1, 2, 3, 4, 5])
print("Elements from index 0 to 1:", array[0:2])
print("Elements from index 1:", array[1:])
print("Elements up to index 3:", array[:3])
print("Alternate elements starting from index 0:", array[0::2])

Elements from index 0 to 1: [1 2]
Elements from index 1: [2 3 4 5]
Elements up to index 3: [1 2 3]
Alternate elements starting from index 0: [1 3 5]


In [48]:
## slicing a 2D array
array = np.array([[1, 2, 3], [4, 5, 6]])
print("Elements from rows 0 to 1 and columns 0 to 1:\n", array[0:2, 0:2])
print("Elements from rows 0 to 1 and all columns:\n", array[0:2, :])
print("Elements from all rows and columns 1 to 2:\n", array[:, 1:])
print("Elements from all rows and first column:\n", array[:, 0])
print("Elements from rows 0 to 1 and alternate columns:\n", array[0:2, 0::2])
print("Elements from last row and all columns:\n", array[-1])
print("Element from last row and last column:\n", array[-1, -1])

Elements from rows 0 to 1 and columns 0 to 1:
 [[1 2]
 [4 5]]
Elements from rows 0 to 1 and all columns:
 [[1 2 3]
 [4 5 6]]
Elements from all rows and columns 1 to 2:
 [[2 3]
 [5 6]]
Elements from all rows and first column:
 [1 4]
Elements from rows 0 to 1 and alternate columns:
 [[1 3]
 [4 6]]
Elements from last row and all columns:
 [4 5 6]
Element from last row and last column:
 6


#### Fancy Indexing

* Fancy indexing allows you to access multiple elements at once using arrays of indices.

In [53]:
## fancy indexing a 1D array
array = np.array([1, 2, 3, 4, 5])
indices = [1, 3]
print("Elements at indices 1 and 3:", array[indices])

Elements at indices 1 and 3: [2 4]


In [57]:
## fancy indexing a 2D array
array = np.array([[1, 2, 3], [4, 5, 6]])
row_indices = [1]
column_indices = [0, 2]
print("Elements at row 1 and columns 0 and 2:\n", array[row_indices, column_indices])
print("All elements at columns 0 and 2:\n", array[:, column_indices])
print("All elements at row 1:\n", array[row_indices, :])

Elements at row 1 and columns 0 and 2:
 [4 6]
All elements at columns 0 and 2:
 [[1 3]
 [4 6]]
All elements at row 1:
 [[4 5 6]]


#### Boolean Indexing

* Boolean indexing allows you to select elements based on conditions.

In [58]:
## boolean indexing a 1D array
array = np.array([1, 2, 3, 4, 5])
mask = array > 2
print("Elements greater than 2:", array[mask])

Elements greater than 2: [3 4 5]


In [60]:
## boolean indexing a 2D array
array = np.array([[1, 2, 3], [4, 5, 6]])
mask = array > 2
print("Elements greater than 2:\n", array[mask])
print("Elements greater than 2 in first row:\n", array[0, mask[0]])

Elements greater than 2:
 [3 4 5 6]
Elements greater than 2 in first row:
 [3]


## Array Manipulation

### Reshaping Arrays

### Transposing Arrays

### Array Concatenation & Stacking

#### Vertical Stacking

#### Horizontal Stacking

### Splitting Arrays

### Adding/Removing Elements

### Copying Arrays

## Array Operations

### Basic Operations

#### Addition

#### Substraction

#### Multiplication

#### Dot Product

#### Scalar Multiplication (Broadcasting)

### Statistical Operations

#### Finding Mean, Median, Mode

#### Finding Minimum and maximum of an array

### Sorting & Searching

## Helpful Functions

### Copying Arrays

### Comparing Array Elements using isclose()

### Converting Array Elment Types

## Linear Equations as Matrices 

### Evaluating Determinant

### Solving Linear Equations

## Finding Eigenvalues and Eigenvectors

## Create Covariance Matrix

## Finding Inverse of a Matrix

## Image Handling